package sec.info.stegchan;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class StegchanApplication {
	//Author: Thomas Sullivan, generated by Spring
	public static void main(String[] args) {
		SpringApplication.run(StegchanApplication.class, args);
	}

}
